### PR TITLE
Document New Jetty config / thread pool #133

### PR DESCRIPTION
**Pull request by rymsha**

### CODE REVIEW

**Comment by rymsha** [comment]
These are new. Not possible to set them before 7.3

**Comment by sigdestad** [comment]
Then the docs need a small note about "stuff below here is new as of 7.3" before we merge

**Comment by alansemenov** [comment]
Like this maybe?

image

**Comment by sigdestad** [comment]
Good suggestion, but this should not require looking up and loading 3rd party stuff imho.

**Comment by alansemenov** [comment]
It's not a 3rd party, it's a local SVG I made.

**Comment by alansemenov** [comment]
None of us understood whether my suggestion was approved or not. Is it ok to use a local svg to mark new features?

**Comment by sigdestad** [comment]
Can I merge this now?

**Comment by rymsha** [comment]
@alansemenov need to include his changes with SVG first.

**Comment by alansemenov** [comment]
https://developer.enonic.com/docs/xp/unstable/deployment/config#jetty

**Pull request merged**
