### PR TITLE
Add cluster docs #175

### PR DESCRIPTION
**Pull request by gbbirkisson**

### CODE REVIEW

**Review by sigdestad — CHANGES_REQUESTED** [review]
Hi. This is a good start, but I hope we can make a few changes.

1. Docker compose is a very particular way of clustering containers. We don't need to have a hands on example of how to start a cluster, but if you still want to include docker-compose, it should be moved to a separate section of the documentation.

2. The docker compose part was was very confusing to me because. 
a) I might not plan or want to use it
b) We show examples of how to do things, but recommend not doing things this way.
c) It gets harder to understand what is dc and not?

2. Load balancer recommendations are missing

3. Files/volumes. are very important, and an area where people tend to fail. Perhaps we should start off earlier in the docs by talking about how XP stores data and which volumes should be created and mounted where. Also, I did not see anything about dumps? Since dumps can be so big this is one of the critical things that should be stored on a separate volume.

4. Finally, I think it would be nice to copy the image of the "basic cluster" into this doc in the intro?

There are also other minor typos, but we can deal with this later :-)

**Comment by gbbirkisson** [comment]
>        a) I might not plan or want to use it

Should I assume people use docker? Or should I not even include that?

**Comment by sigdestad** [comment]
Good question. I think we can even drop that... Let's keep it barebone, and rather write a pure guide on setting up a cluster where we include things like "standard apps", backup and more. Then this will be reference on what you need to consider when setting up a cluster.

**Comment by gbbirkisson** [comment]
Guide updated. Please review again.

**Review by sigdestad — APPROVED** [review]

**Pull request merged**
